name: audio_files_demo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.14.2
  cupertino_icons: ^0.1.2
  web_socket_channel: ^1.1.0
  connectivity: ^0.4.5+6
  fluttertoast: ^3.1.3
  socket_io_client: ^0.9.9
  adhara_socket_io:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/